name: Run private Wayflyer GitHub action.
description: |
  GitHub action to run another GitHub action defined in a private Wayflyer repository.
inputs:
  action:
    description: |
      The GitHub action to run, relative to the `wayflyer` organization.
      For example: "setup-python@v1"
    required: true
    type: string
  github-token:
    description: |
      A GitHub personal access token to authenticate with the private action repository.
    required: true
    type: string
  with:
    description: |
      A YAML string containing the `with` clause for the private action.
    default: ""
    required: true
    type: string
runs:
  using: composite
  steps:
    # Parse inputs.
    - name: Parse inputs
      uses: actions/github-script@v6
      id: parse-inputs
      env:
        WF_INPUT_ACTION: ${{ inputs.action }}
        WF_INPUT_WITH: ${{ inputs.with }}
      with:
        script: return require("lib/index.js").parseInputs()
    # Check out the private action into `.private-action`. Ideally we'd use a temporary directory in `/tmp`, but
    # `uses` requires local actions to start with ".".
    - name: Check out private action
      uses: actions/checkout@v3
      with:
        repository: wayflyer/${{ fromJSON(steps.parse-inputs.outputs.result).repository }}
        ref: ${{ fromJSON(steps.parse-inputs.outputs.result).ref }}
        token: ${{ inputs.github-token }}
        persist-credentials: false
        path: ./.private-action
    # Run the private action, using the deserialized inputs.
    - name: Run private action
      uses: ./.private-action
      with: ${{ fromJSON(steps.parse-inputs.outputs.result).with }}
    # Clean up the private action directory.
    - name: Clean up action
      shell: bash
      run: rm -r ./.private-action
