name: Run private Wayflyer GitHub action.
description: |
  GitHub action to run another GitHub action defined in a private Wayflyer repository.
inputs:
  action:
    description: |
      The GitHub action to run, relative to the `wayflyer` organization.
      For example: "setup-python@v1"
    required: true
    type: string
  github-token:
    description: |
      A GitHub personal access token to authenticate with the private action repository.
    required: true
    type: string
  with:
    description: |
      A YAML string containing the `with` clause for the private action.
    default: ""
    required: true
    type: string
runs:
  using: composite
  steps:
    # Parse the input `action` into a repository and tag.
    - name: Parse action repository
      uses: actions/github-script@v6
      id: parse-action-repository
      env:
        WF_ACTION: ${{ inputs.action }}
      with:
        script: require("lib/index.js").parseAction().repository
        result-encoding: string
    - name: Parse action ref
      uses: actions/github-script@v6
      id: parse-action-ref
      env:
        WF_ACTION: ${{ inputs.action }}
      with:
        script: script: require("lib/index.js").parseAction().ref
        result-encoding: string
    - name: Check out wayflyer/${{ steps.parse-action-repository.outputs.result }}@${{ steps.parse-action-ref.outputs.result }}
      uses: actions/checkout@v3
      with:
        repository: wayflyer/${{ steps.parse-action-repository.outputs.result }}
        ref: ${{ steps.parse-action-ref.outputs.result }}
        token: ${{ inputs.github-token }}
        persist-credentials: false
        path: ./.private-action
    - name: Run wayflyer/${{ steps.parse-action-repository.outputs.result }}@${{ steps.parse-action-ref.outputs.result }}
      uses: ./.private-action
      with: ${{ fromJSON(inputs.with) }}
    - name: Clean up action
      shell: bash
      run: rm -r ./.private-action
